spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog_jpa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect


logging:
  level:
    root: info
    com.fzshuai: debug
  file:
    name: log/blog-dev.log



